# Generated by Django 4.2.19 on 2025-03-08 16:16

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_article_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
