# Generated by Django 4.2.19 on 2025-03-13 12:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0006_article_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='saves',
            field=models.ManyToManyField(blank=True, related_name='saved_articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
