# Generated by Django 4.2.19 on 2025-03-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='downvote_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='upvote_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
