# Generated by Django 4.2.19 on 2025-03-10 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_comment_downvote_count_comment_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='downvote_count',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='upvote_count',
        ),
        migrations.AddField(
            model_name='comment',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
