# Generated by Django 4.2.19 on 2025-03-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_comment_downvote_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notifications_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
